/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiComponents;

import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import railway.database.TicketQuery;

/**
 *
 * @author ryder
 */
public class BookingSuccess extends javax.swing.JFrame {
    
    private int user_id;
    private String username;
    private String first_name;
    private int passenger_id;
    private String passenger_name;
    private String source_name;
    private String destination_name;
    private String coach_type;
    private int num_of_pass;
    private int train_id;
    private String train_name;
    private String arrival_time;
    private String departure_time;
    private DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    private Date today = new Date();
    private Date tomorrow = new Date(today.getTime() + (1000 * 60 * 60 * 24));

    /**
     * Creates new form BookingSuccess
     */
    public BookingSuccess() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void setUserId(int user_id) {
        this.user_id = user_id;
    }
    
    public void setPassengerId(int passenger_id) {
        this.passenger_id = passenger_id;
    }
    
    public void setPassengerName(String passenger_name) {
        this.passenger_name = passenger_name;
    }
    
    public void setSourceName(String source) {
        this.source_name = source;
    }
    
    public void setDestinationName(String destination) {
        this.destination_name = destination;
    }
    
    public void setCoachType(String coach_type) {
        this.coach_type = coach_type;
    }
    
    public void setNumOfPass(int num_of_pass) {
        this.num_of_pass = num_of_pass;
    }
    
    public void setTrainId(int train_id) {
        this.train_id = train_id;
    }
    
    public void setTrainName(String train_name) {
        this.train_name = train_name;
    }
    
    public void setArrivalTime(String arrival_time) {
        this.arrival_time = arrival_time;
    }
    
    public void setDepartureTime(String departure_time) {
        this.departure_time = departure_time;
    }
    
    public void setFirstName(String first_name) {
        this.first_name = first_name;
    }

    public void setUsername(String user_name) {
        this.username = user_name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3Dashboard = new javax.swing.JLabel();
        jPanelCancel = new javax.swing.JPanel();
        jLabelCancel = new javax.swing.JLabel();
        jPanelMinimize = new javax.swing.JPanel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12TommarrowDate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16Source = new javax.swing.JLabel();
        jLabel17Destination = new javax.swing.JLabel();
        jLabel18CoachType = new javax.swing.JLabel();
        jLabel19NumOfPass = new javax.swing.JLabel();
        jLabel20TrainName = new javax.swing.JLabel();
        jLabel21ArrivalTime = new javax.swing.JLabel();
        jLabel22DepartureTime = new javax.swing.JLabel();
        jLabel23TodayDate = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25TicketID = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27PassengerName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(10, 48, 78));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/images/Railway_Logo(W-200).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Indian Railways");

        jLabel3Dashboard.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3Dashboard.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel3Dashboard.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/images/dashboard (1).png"))); // NOI18N
        jLabel3Dashboard.setText("Dashboard");
        jLabel3Dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3Dashboard.setOpaque(true);
        jLabel3Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3DashboardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        jPanelCancel.setBackground(new java.awt.Color(220, 220, 220));
        jPanelCancel.setForeground(new java.awt.Color(51, 51, 51));

        jLabelCancel.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabelCancel.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCancel.setText("X");
        jLabelCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCancelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCancelLayout = new javax.swing.GroupLayout(jPanelCancel);
        jPanelCancel.setLayout(jPanelCancelLayout);
        jPanelCancelLayout.setHorizontalGroup(
            jPanelCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCancelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCancelLayout.setVerticalGroup(
            jPanelCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCancelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanelCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, -1, -1));

        jPanelMinimize.setBackground(new java.awt.Color(220, 220, 220));

        jLabelMinimize.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(51, 51, 51));
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelMinimizeLayout = new javax.swing.GroupLayout(jPanelMinimize);
        jPanelMinimize.setLayout(jPanelMinimizeLayout);
        jPanelMinimizeLayout.setHorizontalGroup(
            jPanelMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMinimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelMinimizeLayout.setVerticalGroup(
            jPanelMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMinimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 50, 50));

        jLabel5.setBackground(new java.awt.Color(44, 44, 44));
        jLabel5.setFont(new java.awt.Font("Jamrul", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Booking Success");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));

        jLabel6.setBackground(new java.awt.Color(44, 44, 44));
        jLabel6.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Source :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, -1, -1));

        jLabel7.setBackground(new java.awt.Color(44, 44, 44));
        jLabel7.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Valid Till :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 660, 110, -1));

        jLabel8.setBackground(new java.awt.Color(44, 44, 44));
        jLabel8.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("No. of Passenger :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 200, -1));

        jLabel9.setBackground(new java.awt.Color(44, 44, 44));
        jLabel9.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Destination :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/images/greenTick.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 190, 110));

        jLabel12TommarrowDate.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel12TommarrowDate.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12TommarrowDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel12TommarrowDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 660, 380, 30));

        jLabel10.setBackground(new java.awt.Color(44, 44, 44));
        jLabel10.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Coach type :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 130, -1));

        jLabel11.setBackground(new java.awt.Color(44, 44, 44));
        jLabel11.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Train Name :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 140, -1));

        jLabel13.setBackground(new java.awt.Color(44, 44, 44));
        jLabel13.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Arrival Time :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 140, -1));

        jLabel14.setBackground(new java.awt.Color(44, 44, 44));
        jLabel14.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Departure Time :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 180, -1));

        jLabel15.setBackground(new java.awt.Color(44, 44, 44));
        jLabel15.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Date :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, 70, -1));

        jLabel16Source.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel16Source.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16Source.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel16Source, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 380, 30));

        jLabel17Destination.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel17Destination.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17Destination.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel17Destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 380, 30));

        jLabel18CoachType.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel18CoachType.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18CoachType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel18CoachType, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 380, 30));

        jLabel19NumOfPass.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel19NumOfPass.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19NumOfPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel19NumOfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 380, 30));

        jLabel20TrainName.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel20TrainName.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20TrainName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel20TrainName, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 380, 30));

        jLabel21ArrivalTime.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel21ArrivalTime.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21ArrivalTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel21ArrivalTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 540, 380, 30));

        jLabel22DepartureTime.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel22DepartureTime.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22DepartureTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel22DepartureTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, 380, 30));

        jLabel23TodayDate.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel23TodayDate.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23TodayDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel23TodayDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, 380, 30));

        jLabel24.setBackground(new java.awt.Color(44, 44, 44));
        jLabel24.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Ticket ID :");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, -1, -1));

        jLabel25TicketID.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel25TicketID.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25TicketID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel25TicketID, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 380, 30));

        jLabel26.setBackground(new java.awt.Color(44, 44, 44));
        jLabel26.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Passenger Name :");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, -1));

        jLabel27PassengerName.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel27PassengerName.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27PassengerName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel27PassengerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 380, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCancelMouseClicked

    private void jLabelCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelMouseEntered
        // TODO add your handling code here:
        jLabelCancel.setForeground(Color.white);
        jPanelCancel.setBackground(new Color(204, 0, 0));
    }//GEN-LAST:event_jLabelCancelMouseEntered

    private void jLabelCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelMouseExited
        // TODO add your handling code here:
        jLabelCancel.setForeground(new Color(51, 51, 51));
        jPanelCancel.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_jLabelCancelMouseExited

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseEntered
        // TODO add your handling code here:
        jLabelMinimize.setForeground(Color.white);
        jPanelMinimize.setBackground(new Color(200, 200, 200));
    }//GEN-LAST:event_jLabelMinimizeMouseEntered

    private void jLabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseExited
        // TODO add your handling code here:
        jLabelMinimize.setForeground(new Color(51, 51, 51));
        jPanelMinimize.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_jLabelMinimizeMouseExited

    private void jLabel3DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3DashboardMouseClicked
        // TODO add your handling code here:
        UserDashboard supf = new UserDashboard();
        supf.setUserId(user_id);
        supf.setUsername(username);
        supf.setFirstName(first_name);
        supf.setVisible(true);
        supf.pack();
        supf.setLocationRelativeTo(null);
        supf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel3DashboardMouseClicked
    
    public void setLablesOnTicket() {
        jLabel27PassengerName.setText(passenger_name);
        jLabel16Source.setText(source_name);
        jLabel17Destination.setText(destination_name);
        jLabel18CoachType.setText(coach_type);
        jLabel19NumOfPass.setText(String.valueOf(num_of_pass));
        jLabel20TrainName.setText(train_name);
        jLabel21ArrivalTime.setText(arrival_time);
        jLabel22DepartureTime.setText(departure_time);
        jLabel23TodayDate.setText(String.valueOf(df.format(today)));
        jLabel12TommarrowDate.setText(String.valueOf(df.format(tomorrow)));
    }
    
    public void bookTicket() {
        TicketQuery tq = new TicketQuery();
        int ticket_id = tq.newTicket(user_id, train_id, passenger_id, source_name, destination_name, num_of_pass, coach_type, today, tomorrow);
        jLabel25TicketID.setText(String.valueOf(ticket_id));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingSuccess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12TommarrowDate;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16Source;
    private javax.swing.JLabel jLabel17Destination;
    private javax.swing.JLabel jLabel18CoachType;
    private javax.swing.JLabel jLabel19NumOfPass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20TrainName;
    private javax.swing.JLabel jLabel21ArrivalTime;
    private javax.swing.JLabel jLabel22DepartureTime;
    private javax.swing.JLabel jLabel23TodayDate;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25TicketID;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27PassengerName;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3Dashboard;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCancel;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCancel;
    private javax.swing.JPanel jPanelMinimize;
    // End of variables declaration//GEN-END:variables
}
