/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiComponents;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import railway.database.TicketQuery;

/**
 *
 * @author ryder
 */
public class CancelTicket extends javax.swing.JFrame {

    private String first_name;
    private String username;
    private int user_id;

    /**
     * Creates new form CancelTicket
     */
    public CancelTicket() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void setFirstName(String first_name) {
        this.first_name = first_name;
    }

    public void setUsername(String user_name) {
        this.username = user_name;
    }

    public void setUserId(int user_id) {
        this.user_id = user_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3Dashboard = new javax.swing.JLabel();
        jPanelCancel = new javax.swing.JPanel();
        jLabelCancel = new javax.swing.JLabel();
        jPanelMinimize = new javax.swing.JPanel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12TommarrowDate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16Source = new javax.swing.JLabel();
        jLabel17Destination = new javax.swing.JLabel();
        jLabel18CoachType = new javax.swing.JLabel();
        jLabel19NumOfPass = new javax.swing.JLabel();
        jLabel20TrainName = new javax.swing.JLabel();
        jLabel21ArrivalTime = new javax.swing.JLabel();
        jLabel22DepartureTime = new javax.swing.JLabel();
        jLabel23TodayDate = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27PassengerName = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField2TicketID = new javax.swing.JTextField();
        jButton2CancelTicket = new javax.swing.JButton();
        jButton2GetTicket1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(10, 48, 78));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/images/Railway_Logo(W-200).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Indian Railways");

        jLabel3Dashboard.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3Dashboard.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel3Dashboard.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/images/dashboard (1).png"))); // NOI18N
        jLabel3Dashboard.setText("Dashboard");
        jLabel3Dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3Dashboard.setOpaque(true);
        jLabel3Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3DashboardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        jPanelCancel.setBackground(new java.awt.Color(220, 220, 220));
        jPanelCancel.setForeground(new java.awt.Color(51, 51, 51));

        jLabelCancel.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabelCancel.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCancel.setText("X");
        jLabelCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCancelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCancelLayout = new javax.swing.GroupLayout(jPanelCancel);
        jPanelCancel.setLayout(jPanelCancelLayout);
        jPanelCancelLayout.setHorizontalGroup(
            jPanelCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCancelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCancelLayout.setVerticalGroup(
            jPanelCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCancelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanelCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, -1, -1));

        jPanelMinimize.setBackground(new java.awt.Color(220, 220, 220));

        jLabelMinimize.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(51, 51, 51));
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelMinimizeLayout = new javax.swing.GroupLayout(jPanelMinimize);
        jPanelMinimize.setLayout(jPanelMinimizeLayout);
        jPanelMinimizeLayout.setHorizontalGroup(
            jPanelMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMinimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelMinimizeLayout.setVerticalGroup(
            jPanelMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMinimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 50, 50));

        jLabel5.setBackground(new java.awt.Color(44, 44, 44));
        jLabel5.setFont(new java.awt.Font("Jamrul", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Enter Ticket ID :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        jLabel6.setBackground(new java.awt.Color(44, 44, 44));
        jLabel6.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Source :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, -1));

        jLabel7.setBackground(new java.awt.Color(44, 44, 44));
        jLabel7.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Valid Till :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 640, 110, -1));

        jLabel8.setBackground(new java.awt.Color(44, 44, 44));
        jLabel8.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("No. of Passenger :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 200, -1));

        jLabel9.setBackground(new java.awt.Color(44, 44, 44));
        jLabel9.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Destination :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 120, -1));

        jLabel12TommarrowDate.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel12TommarrowDate.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12TommarrowDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel12TommarrowDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 640, 380, 30));

        jLabel10.setBackground(new java.awt.Color(44, 44, 44));
        jLabel10.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Coach type :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 130, -1));

        jLabel11.setBackground(new java.awt.Color(44, 44, 44));
        jLabel11.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Train Name :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 140, -1));

        jLabel13.setBackground(new java.awt.Color(44, 44, 44));
        jLabel13.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Arrival Time :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, 140, -1));

        jLabel14.setBackground(new java.awt.Color(44, 44, 44));
        jLabel14.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Departure Time :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 180, -1));

        jLabel15.setBackground(new java.awt.Color(44, 44, 44));
        jLabel15.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Booking Date :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, 150, -1));

        jLabel16Source.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel16Source.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16Source.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel16Source, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 380, 30));

        jLabel17Destination.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel17Destination.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17Destination.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel17Destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 380, 30));

        jLabel18CoachType.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel18CoachType.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18CoachType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel18CoachType, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 380, 30));

        jLabel19NumOfPass.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel19NumOfPass.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19NumOfPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel19NumOfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 380, 30));

        jLabel20TrainName.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel20TrainName.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20TrainName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel20TrainName, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 380, 30));

        jLabel21ArrivalTime.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel21ArrivalTime.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21ArrivalTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel21ArrivalTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, 380, 30));

        jLabel22DepartureTime.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel22DepartureTime.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22DepartureTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel22DepartureTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, 380, 30));

        jLabel23TodayDate.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel23TodayDate.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23TodayDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel23TodayDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 600, 380, 30));

        jLabel26.setBackground(new java.awt.Color(44, 44, 44));
        jLabel26.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Passenger Name :");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));

        jLabel27PassengerName.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel27PassengerName.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27PassengerName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel27PassengerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 380, 30));

        jLabel12.setBackground(new java.awt.Color(44, 44, 44));
        jLabel12.setFont(new java.awt.Font("Jamrul", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Ticket Information");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));

        jTextField2TicketID.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2TicketID.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jTextField2TicketID.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2TicketID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.add(jTextField2TicketID, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 580, 30));

        jButton2CancelTicket.setBackground(new java.awt.Color(255, 51, 51));
        jButton2CancelTicket.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jButton2CancelTicket.setForeground(new java.awt.Color(255, 255, 255));
        jButton2CancelTicket.setText("Cancel");
        jButton2CancelTicket.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButton2CancelTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CancelTicketActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2CancelTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 690, 100, 40));

        jButton2GetTicket1.setBackground(new java.awt.Color(10, 48, 78));
        jButton2GetTicket1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jButton2GetTicket1.setForeground(new java.awt.Color(255, 255, 255));
        jButton2GetTicket1.setText("Get Info");
        jButton2GetTicket1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButton2GetTicket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2GetTicket1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2GetTicket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCancelMouseClicked

    private void jLabelCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelMouseEntered
        // TODO add your handling code here:
        jLabelCancel.setForeground(Color.white);
        jPanelCancel.setBackground(new Color(204, 0, 0));
    }//GEN-LAST:event_jLabelCancelMouseEntered

    private void jLabelCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelMouseExited
        // TODO add your handling code here:
        jLabelCancel.setForeground(new Color(51, 51, 51));
        jPanelCancel.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_jLabelCancelMouseExited

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseEntered
        // TODO add your handling code here:
        jLabelMinimize.setForeground(Color.white);
        jPanelMinimize.setBackground(new Color(200, 200, 200));
    }//GEN-LAST:event_jLabelMinimizeMouseEntered

    private void jLabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseExited
        // TODO add your handling code here:
        jLabelMinimize.setForeground(new Color(51, 51, 51));
        jPanelMinimize.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_jLabelMinimizeMouseExited

    private void clearFields() {
        jLabel12TommarrowDate.setText("");
        jLabel16Source.setText("");
        jLabel17Destination.setText("");
        jLabel18CoachType.setText("");
        jLabel19NumOfPass.setText("");
        jLabel20TrainName.setText("");
        jLabel21ArrivalTime.setText("");
        jLabel22DepartureTime.setText("");
        jLabel23TodayDate.setText("");
        jLabel27PassengerName.setText("");
        jTextField2TicketID.setText("");
    }

    private void jButton2CancelTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CancelTicketActionPerformed
        // TODO add your handling code here:
        if (jLabel12TommarrowDate.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Ticket Id");
        } else {
            TicketQuery tq = new TicketQuery();
            if (tq.cancelTicket(Integer.parseInt(jTextField2TicketID.getText()), jLabel18CoachType.getText(), Integer.parseInt(jLabel19NumOfPass.getText()), jLabel20TrainName.getText())) {
                JOptionPane.showMessageDialog(this, "Ticket Cancel Successfull");
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Something went wrong");
            }
        }
    }//GEN-LAST:event_jButton2CancelTicketActionPerformed

    private void jButton2GetTicket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2GetTicket1ActionPerformed
        // TODO add your handling code here:
        if (jTextField2TicketID.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Ticket Id");
        } else {
            TicketQuery tq = new TicketQuery();
            String[] ticket = tq.getTicketInfo(Integer.parseInt(jTextField2TicketID.getText()));
            if (ticket[0] == null) {
                JOptionPane.showMessageDialog(this, "No Ticket with Ticket Id : " + String.valueOf(jTextField2TicketID.getText()) + " is available");
            } else {
                jLabel27PassengerName.setText(ticket[1]);
                jLabel16Source.setText(ticket[2]);
                jLabel17Destination.setText(ticket[3]);
                jLabel18CoachType.setText(ticket[4]);
                jLabel19NumOfPass.setText(ticket[5]);
                jLabel20TrainName.setText(ticket[6]);
                jLabel21ArrivalTime.setText(ticket[7]);
                jLabel22DepartureTime.setText(ticket[8]);
                jLabel23TodayDate.setText(ticket[9]);
                jLabel12TommarrowDate.setText(ticket[10]);
            }
        }

    }//GEN-LAST:event_jButton2GetTicket1ActionPerformed

    private void jLabel3DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3DashboardMouseClicked
        // TODO add your handling code here:
        UserDashboard supf = new UserDashboard();
        supf.setUserId(user_id);
        supf.setUsername(username);
        supf.setFirstName(first_name);
        supf.setVisible(true);
        supf.pack();
        supf.setLocationRelativeTo(null);
        supf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel3DashboardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2CancelTicket;
    private javax.swing.JButton jButton2GetTicket1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel12TommarrowDate;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16Source;
    private javax.swing.JLabel jLabel17Destination;
    private javax.swing.JLabel jLabel18CoachType;
    private javax.swing.JLabel jLabel19NumOfPass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20TrainName;
    private javax.swing.JLabel jLabel21ArrivalTime;
    private javax.swing.JLabel jLabel22DepartureTime;
    private javax.swing.JLabel jLabel23TodayDate;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27PassengerName;
    private javax.swing.JLabel jLabel3Dashboard;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCancel;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCancel;
    private javax.swing.JPanel jPanelMinimize;
    private javax.swing.JTextField jTextField2TicketID;
    // End of variables declaration//GEN-END:variables
}
