/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiComponents;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import railway.database.PassengerQuery;

/**
 *
 * @author ryder
 */
public class PassengerInfo extends javax.swing.JFrame {

    private int user_id;
    private String username;
    private String first_name;
    

    /**
     * Creates new form BookTicket
     */
    public PassengerInfo() {
        initComponents();
        //Center Form
        this.setLocationRelativeTo(null);
    }

    public void setUserId(int user_id) {
        this.user_id = user_id;
    }
    
    public void setFirstName(String first_name) {
        this.first_name = first_name;
    }

    public void setUsername(String user_name) {
        this.username = user_name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelCancel = new javax.swing.JPanel();
        jLabelCancel = new javax.swing.JLabel();
        jPanelMinimize = new javax.swing.JPanel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPassengerId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8Pincode = new javax.swing.JLabel();
        jLabel12PassngerId = new javax.swing.JLabel();
        jLabel14FullName = new javax.swing.JLabel();
        jLabel15Gender = new javax.swing.JLabel();
        jLabel17Contact = new javax.swing.JLabel();
        jLabel18State = new javax.swing.JLabel();
        jButtonBookTicketBtn = new javax.swing.JButton();
        jButtonGetInfoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(10, 48, 78));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/images/Railway_Logo(W-200).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Indian Railways");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelCancel.setBackground(new java.awt.Color(220, 220, 220));
        jPanelCancel.setForeground(new java.awt.Color(51, 51, 51));

        jLabelCancel.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabelCancel.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCancel.setText("X");
        jLabelCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCancelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCancelLayout = new javax.swing.GroupLayout(jPanelCancel);
        jPanelCancel.setLayout(jPanelCancelLayout);
        jPanelCancelLayout.setHorizontalGroup(
            jPanelCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCancelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCancelLayout.setVerticalGroup(
            jPanelCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCancelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanelCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, -1, -1));

        jPanelMinimize.setBackground(new java.awt.Color(220, 220, 220));

        jLabelMinimize.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(51, 51, 51));
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelMinimizeLayout = new javax.swing.GroupLayout(jPanelMinimize);
        jPanelMinimize.setLayout(jPanelMinimizeLayout);
        jPanelMinimizeLayout.setHorizontalGroup(
            jPanelMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMinimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelMinimizeLayout.setVerticalGroup(
            jPanelMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMinimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 50, 50));

        jLabel4.setBackground(new java.awt.Color(44, 44, 44));
        jLabel4.setFont(new java.awt.Font("Jamrul", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Passenger Info");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, -1, -1));

        jTextFieldPassengerId.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPassengerId.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jTextFieldPassengerId.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPassengerId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.add(jTextFieldPassengerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 540, 30));

        jLabel3.setBackground(new java.awt.Color(44, 44, 44));
        jLabel3.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Pincode :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 100, -1));

        jLabel16.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Don't have an Passenger Account? Create one here");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 670, -1, -1));

        jLabel5.setBackground(new java.awt.Color(44, 44, 44));
        jLabel5.setFont(new java.awt.Font("Jamrul", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Book Ticket");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, -1, -1));

        jLabel6.setBackground(new java.awt.Color(44, 44, 44));
        jLabel6.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Enter Passenger ID:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 300, -1));

        jLabel7.setBackground(new java.awt.Color(44, 44, 44));
        jLabel7.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Full Name :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 120, -1));

        jLabel9.setBackground(new java.awt.Color(44, 44, 44));
        jLabel9.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Gender :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 90, -1));

        jLabel10.setBackground(new java.awt.Color(44, 44, 44));
        jLabel10.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Contact :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 90, -1));

        jLabel11.setBackground(new java.awt.Color(44, 44, 44));
        jLabel11.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("State :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 70, -1));

        jLabel13.setBackground(new java.awt.Color(44, 44, 44));
        jLabel13.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Passenger ID :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 150, -1));

        jLabel8Pincode.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel8Pincode.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8Pincode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel8Pincode, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, 370, 30));

        jLabel12PassngerId.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel12PassngerId.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12PassngerId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel12PassngerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 370, 30));

        jLabel14FullName.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel14FullName.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14FullName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel14FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 370, 30));

        jLabel15Gender.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel15Gender.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15Gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel15Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 370, 30));

        jLabel17Contact.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel17Contact.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17Contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel17Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 480, 370, 30));

        jLabel18State.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel18State.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18State.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel18State, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 370, 30));

        jButtonBookTicketBtn.setBackground(new java.awt.Color(0, 204, 0));
        jButtonBookTicketBtn.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jButtonBookTicketBtn.setForeground(new java.awt.Color(51, 51, 51));
        jButtonBookTicketBtn.setText("Book Ticket");
        jButtonBookTicketBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonBookTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookTicketBtnActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBookTicketBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 610, 260, 40));

        jButtonGetInfoBtn.setBackground(new java.awt.Color(10, 48, 78));
        jButtonGetInfoBtn.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jButtonGetInfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGetInfoBtn.setText("Get Info");
        jButtonGetInfoBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonGetInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetInfoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGetInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCancelMouseClicked

    private void jLabelCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelMouseEntered
        // TODO add your handling code here:
        jLabelCancel.setForeground(Color.white);
        jPanelCancel.setBackground(new Color(204, 0, 0));
    }//GEN-LAST:event_jLabelCancelMouseEntered

    private void jLabelCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelMouseExited
        // TODO add your handling code here:
        jLabelCancel.setForeground(new Color(51, 51, 51));
        jPanelCancel.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_jLabelCancelMouseExited

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseEntered
        // TODO add your handling code here:
        jLabelMinimize.setForeground(Color.white);
        jPanelMinimize.setBackground(new Color(200, 200, 200));
    }//GEN-LAST:event_jLabelMinimizeMouseEntered

    private void jLabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseExited
        // TODO add your handling code here:
        jLabelMinimize.setForeground(new Color(51, 51, 51));
        jPanelMinimize.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_jLabelMinimizeMouseExited

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        PassengerSignup supf = new PassengerSignup();
        supf.setUserId(user_id);
        supf.setUsername(username);
        supf.setFirstName(first_name);
        supf.setVisible(true);
        supf.pack();
        supf.setLocationRelativeTo(null);
        supf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jButtonBookTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookTicketBtnActionPerformed
        // TODO add your handling code here:
        if (verifyData()) {
            BookTicket supf = new BookTicket();
            supf.setUserId(user_id);
            supf.setUsername(username);
            supf.setFirstName(first_name);
            supf.setPassengerId(Integer.parseInt(jLabel12PassngerId.getText()));
            supf.setPassengerName(jLabel14FullName.getText());
            supf.setVisible(true);
            supf.pack();
            supf.setLocationRelativeTo(null);
            supf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonBookTicketBtnActionPerformed

    private boolean verifyData() {
        if (jTextFieldPassengerId.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Passenger ID");
            return false;
        } else {
            return true;
        }
    }

    private void jButtonGetInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetInfoBtnActionPerformed
        // TODO add your handling code here:
        if (verifyData()) {
            PassengerQuery pq = new PassengerQuery();
            String[] passenger = pq.getPassengerDeatils(Integer.parseInt(jTextFieldPassengerId.getText()));
            if (passenger[0] != null) {
                jLabel12PassngerId.setText(passenger[0]);
                jLabel14FullName.setText(passenger[1]);
                jLabel15Gender.setText(passenger[2]);
                jLabel17Contact.setText(passenger[3]);
                jLabel18State.setText(passenger[4]);
                jLabel8Pincode.setText(passenger[5]);
            } else {
                JOptionPane.showMessageDialog(this, "No such passnger ID");
            }
        }
    }//GEN-LAST:event_jButtonGetInfoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBookTicketBtn;
    private javax.swing.JButton jButtonGetInfoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12PassngerId;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14FullName;
    private javax.swing.JLabel jLabel15Gender;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17Contact;
    private javax.swing.JLabel jLabel18State;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8Pincode;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCancel;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCancel;
    private javax.swing.JPanel jPanelMinimize;
    private javax.swing.JTextField jTextFieldPassengerId;
    // End of variables declaration//GEN-END:variables
}
