package GuiComponents;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import railway.database.UserQuery;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ryder
 */
public class UserSignUp extends javax.swing.JFrame {

    /**
     * Creates new form UserSignUp
     */
    public UserSignUp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelCancel = new javax.swing.JPanel();
        jLabelCancel = new javax.swing.JLabel();
        jPanelMinimize = new javax.swing.JPanel();
        jLabelMinimize = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jCheckBoxShowPass = new javax.swing.JCheckBox();
        jButtonSignupBtn = new javax.swing.JButton();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAdharNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldMobile = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCity = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldState = new javax.swing.JTextField();
        jTextFieldPincode = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/images/Railway_Logo(W-200).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Indian Railways");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        jPanelCancel.setBackground(new java.awt.Color(220, 220, 220));
        jPanelCancel.setForeground(new java.awt.Color(51, 51, 51));

        jLabelCancel.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabelCancel.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCancel.setText("X");
        jLabelCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCancelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCancelLayout = new javax.swing.GroupLayout(jPanelCancel);
        jPanelCancel.setLayout(jPanelCancelLayout);
        jPanelCancelLayout.setHorizontalGroup(
            jPanelCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCancelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCancelLayout.setVerticalGroup(
            jPanelCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCancelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanelCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, -1, -1));

        jPanelMinimize.setBackground(new java.awt.Color(220, 220, 220));

        jLabelMinimize.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(51, 51, 51));
        jLabelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimize.setText("-");
        jLabelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelMinimizeLayout = new javax.swing.GroupLayout(jPanelMinimize);
        jPanelMinimize.setLayout(jPanelMinimizeLayout);
        jPanelMinimizeLayout.setHorizontalGroup(
            jPanelMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMinimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelMinimizeLayout.setVerticalGroup(
            jPanelMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMinimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 50, 50));

        jTextFieldUsername.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUsername.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jTextFieldUsername.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 450, 30));

        jLabel3.setBackground(new java.awt.Color(44, 44, 44));
        jLabel3.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, -1, -1));

        jLabel4.setBackground(new java.awt.Color(44, 44, 44));
        jLabel4.setFont(new java.awt.Font("Jamrul", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Signup");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        jLabel5.setBackground(new java.awt.Color(44, 44, 44));
        jLabel5.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 620, -1, -1));

        jPasswordFieldPassword.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldPassword.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jPasswordFieldPassword.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordFieldPassword.setToolTipText("Password Cannot be changed");
        jPasswordFieldPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 650, 450, 30));

        jCheckBoxShowPass.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxShowPass.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jCheckBoxShowPass.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBoxShowPass.setText("Show Password");
        jCheckBoxShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPassActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 690, -1, -1));

        jButtonSignupBtn.setBackground(new java.awt.Color(102, 0, 255));
        jButtonSignupBtn.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jButtonSignupBtn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSignupBtn.setText("Signup");
        jButtonSignupBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonSignupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignupBtnActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSignupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 710, 100, 40));

        jTextFieldFirstName.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFirstName.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jTextFieldFirstName.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldFirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.add(jTextFieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 220, 30));

        jLabel6.setBackground(new java.awt.Color(44, 44, 44));
        jLabel6.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("First Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        jTextFieldLastName.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldLastName.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jTextFieldLastName.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldLastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.add(jTextFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 220, 30));

        jLabel7.setBackground(new java.awt.Color(44, 44, 44));
        jLabel7.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Last Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, -1, -1));

        jLabel8.setBackground(new java.awt.Color(44, 44, 44));
        jLabel8.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Adhar-Card Number");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        jTextFieldAdharNo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldAdharNo.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jTextFieldAdharNo.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldAdharNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.add(jTextFieldAdharNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 450, 30));

        jLabel9.setBackground(new java.awt.Color(44, 44, 44));
        jLabel9.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Gender");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, -1, -1));

        jLabel10.setBackground(new java.awt.Color(44, 44, 44));
        jLabel10.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Age");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, -1, -1));

        jTextFieldAge.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldAge.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jTextFieldAge.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldAge.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.add(jTextFieldAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 220, 30));

        jComboBoxGender.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxGender.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jComboBoxGender.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", "T" }));
        jComboBoxGender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jPanel1.add(jComboBoxGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 220, -1));

        jTextFieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmail.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 220, 30));

        jLabel11.setBackground(new java.awt.Color(44, 44, 44));
        jLabel11.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Mobile");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, -1));

        jTextFieldMobile.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldMobile.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jTextFieldMobile.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldMobile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.add(jTextFieldMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 220, 30));

        jLabel12.setBackground(new java.awt.Color(44, 44, 44));
        jLabel12.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Email");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, -1, -1));

        jLabel13.setBackground(new java.awt.Color(44, 44, 44));
        jLabel13.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("City");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, -1, -1));

        jTextFieldCity.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCity.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jTextFieldCity.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldCity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.add(jTextFieldCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 220, 30));

        jLabel14.setBackground(new java.awt.Color(44, 44, 44));
        jLabel14.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("State");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, -1, -1));

        jTextFieldState.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldState.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jTextFieldState.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldState.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.add(jTextFieldState, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 220, 30));

        jTextFieldPincode.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPincode.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jTextFieldPincode.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldPincode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.add(jTextFieldPincode, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 450, 30));

        jLabel15.setBackground(new java.awt.Color(44, 44, 44));
        jLabel15.setFont(new java.awt.Font("Jamrul", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Pincode");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, -1, -1));

        jLabel16.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Already have an Account? Login here");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 770, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCancelMouseClicked

    private void jLabelCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelMouseEntered
        // TODO add your handling code here:
        jLabelCancel.setForeground(Color.white);
        jPanelCancel.setBackground(new Color(204, 0, 0));
    }//GEN-LAST:event_jLabelCancelMouseEntered

    private void jLabelCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelMouseExited
        // TODO add your handling code here:
        jLabelCancel.setForeground(new Color(51, 51, 51));
        jPanelCancel.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_jLabelCancelMouseExited

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseEntered
        // TODO add your handling code here:
        jLabelMinimize.setForeground(Color.white);
        jPanelMinimize.setBackground(new Color(200, 200, 200));
    }//GEN-LAST:event_jLabelMinimizeMouseEntered

    private void jLabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseExited
        // TODO add your handling code here:
        jLabelMinimize.setForeground(new Color(51, 51, 51));
        jPanelMinimize.setBackground(new Color(220, 220, 220));
    }//GEN-LAST:event_jLabelMinimizeMouseExited

    private void jCheckBoxShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPassActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxShowPass.isSelected()) {
            jPasswordFieldPassword.setEchoChar((char) 0);
        } else {
            jPasswordFieldPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxShowPassActionPerformed

    private boolean verifyData() {
        UserQuery uq = new UserQuery();
        if (jTextFieldFirstName.getText().equals("")
                || jTextFieldLastName.getText().equals("")
                || jTextFieldAdharNo.getText().equals("")
                || jComboBoxGender.getSelectedItem().equals("")
                || jTextFieldAge.getText().equals("")
                || jTextFieldMobile.getText().equals("")
                || jTextFieldEmail.getText().equals("")
                || jTextFieldCity.getText().equals("")
                || jTextFieldState.getText().equals("")
                || jTextFieldPincode.getText().equals("")
                || jTextFieldUsername.getText().equals("")
                || String.valueOf(jPasswordFieldPassword.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please fill in all the fields");
            return false;
        } else if (uq.isUserExists(jTextFieldUsername.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Username " + jTextFieldUsername.getText() + " already exists.");
            return false;
        } else {
            return true;
        }
    }
    
    private void clearFields () {
        jTextFieldAdharNo.setText("");
        jTextFieldAge.setText("");
        jTextFieldCity.setText("");
        jTextFieldEmail.setText("");
        jTextFieldFirstName.setText("");
        jTextFieldLastName.setText("");
        jTextFieldMobile.setText("");
        jTextFieldPincode.setText("");
        jTextFieldState.setText("");
        jTextFieldUsername.setText("");
        jPasswordFieldPassword.setText("");
        jComboBoxGender.setSelectedIndex(0);
    }

    private void jButtonSignupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignupBtnActionPerformed
        // TODO add your handling code here:
        if (verifyData()) {
            UserQuery uq = new UserQuery();
            uq.createNewUser(jTextFieldFirstName.getText(),
                    jTextFieldLastName.getText(),
                    jTextFieldAdharNo.getText(),
                    String.valueOf(jComboBoxGender.getSelectedItem()),
                    Integer.parseInt(jTextFieldAge.getText()),
                    jTextFieldMobile.getText(),
                    jTextFieldEmail.getText(),
                    jTextFieldCity.getText(),
                    jTextFieldState.getText(),
                    jTextFieldPincode.getText(),
                    jTextFieldUsername.getText(),
                    String.valueOf(jPasswordFieldPassword.getPassword()),
                    "",
                    "");
            JOptionPane.showMessageDialog(this, "User account created. Please login now");
            clearFields();
        }
    }//GEN-LAST:event_jButtonSignupBtnActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        UserLogin supf = new UserLogin();
        supf.setVisible(true);
        supf.pack();
        supf.setLocationRelativeTo(null);
        supf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSignupBtn;
    private javax.swing.JCheckBox jCheckBoxShowPass;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCancel;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCancel;
    private javax.swing.JPanel jPanelMinimize;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldAdharNo;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldMobile;
    private javax.swing.JTextField jTextFieldPincode;
    private javax.swing.JTextField jTextFieldState;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
